### ISSUE TITLE
Buy-Axie script error:  Error buying axie ProviderError: tx fee (400.00 ether) exceeds the configured cap (1.00 ether)

### ISSUE THREAD

**Issue by YouHeDad** [alexx855/axie-ronin-ethers-js-tools#4]
Hi!  

I am just attempting to run the following script, "npx hardhat buy --axie #######", to buy an Axie.

I keep getting the following error, " Error buying axie ProviderError: tx fee (400.00 ether) exceeds the configured cap (1.00 ether)"

I can't seem to find any documentation to troubleshoot this.  400 also seems wrong, for any mavis/axie/ronin fees.

Any ideas?

Thank you!

**Comment by chris101-dev** [comment]
i had the same issue today.
its definetly something that needs to be fixed but short term solution for me was to approve WETH on the contract manually because it seems just to be an issue with the approval of WETH. after that everything worked fine

**Comment by YouHeDad** [comment]
I guess I should be more specific.  After doing some more research and isolating code, I found that this error is related to there being no Allowance on the contract instance.

When there's no allowance, this code is supposed to approve a gas allowance:

`const amountToapproved='115792089237316195423570985008687907853269984665640564039457584007913129639935'
 const txApproveWETH = await wethContract.approve(contract.address, amountToApproved, { gasLimit: DEFAULT_GAS_LIMIT })`

**wethContract.approve()**  is where the 'ProviderError: tx fee exceeds configured cap', is occuring.

I tried to remove it completely, but that ends up in an 'unpredictable gas limit error'


Could this also be because AxieMarketplace gas fees are more recently paid in RON, instead of WETH?

**Comment by YouHeDad** [comment]
> i had the same issue today. its definetly something that needs to be fixed but short term solution for me was to approve WETH on the contract manually because it seems just to be an issue with the approval of WETH. after that everything worked fine

Oh. how did you go about the manual approval?  *ponder*

**Comment by chris101-dev** [comment]
> > i had the same issue today. its definetly something that needs to be fixed but short term solution for me was to approve WETH on the contract manually because it seems just to be an issue with the approval of WETH. after that everything worked fine
> 
> Oh. how did you go about the manual approval? _ponder_

i went to the marketplace, clicked on buy axie, approved weth, and then run my script again and it worked because its skipping the step you specified above. i know its not a fix for the issue but a workaround if you really need to go ahead :)

**Comment by alexx855** [comment]
Hey everyone, thanks for reporting, I did not notice this since i have the allowance approved in my accounts 😅

I've fixed the problem by removing the manual gas limit in the code. You can see the commit here: https://github.com/alexx855/axie-ronin-ethers-js-tools/commit/1b6407d26cd4e52a703128eb2d61b05e4fe31ead#diff-df5ae27217069f74edc8d542cacdf5262f2a5fc8c411bf9090e5a0df92372748L148 

@keimi101 workarround would work too 

I've just published a new version that should have this fix implemented.

**Comment by chris101-dev** [comment]
> Hey everyone, thanks for reporting, I did not notice this since i have the allowance approved in my accounts 😅
> 
> I've fixed the problem by removing the manual gas limit in the code. You can see the commit here: [1b6407d#diff-df5ae27217069f74edc8d542cacdf5262f2a5fc8c411bf9090e5a0df92372748L148](https://github.com/alexx855/axie-ronin-ethers-js-tools/commit/1b6407d26cd4e52a703128eb2d61b05e4fe31ead#diff-df5ae27217069f74edc8d542cacdf5262f2a5fc8c411bf9090e5a0df92372748L148)
> 
> @keimi101 workarround would work too
> 
> I've just published a new version that should have this fix implemented.

ty for the quick fix, btw great work on this repo 👍

**Comment by YouHeDad** [comment]
> Hey everyone, thanks for reporting, I did not notice this since i have the allowance approved in my accounts 😅
> 
> I've fixed the problem by removing the manual gas limit in the code. You can see the commit here: [1b6407d#diff-df5ae27217069f74edc8d542cacdf5262f2a5fc8c411bf9090e5a0df92372748L148](https://github.com/alexx855/axie-ronin-ethers-js-tools/commit/1b6407d26cd4e52a703128eb2d61b05e4fe31ead#diff-df5ae27217069f74edc8d542cacdf5262f2a5fc8c411bf9090e5a0df92372748L148)
> 
> @keimi101 workarround would work too
> 
> I've just published a new version that should have this fix implemented.

Sweet!  It worked!!

Thank you for the quick reply!
